// Curated SAT vocabulary. Definitions, example sentences and word-parts are
// original (written for Ilm AI) — the words themselves are common public SAT
// vocabulary. Progress is tracked client-side (see vocabProgress.ts).

export type VocabDifficulty = "Easy" | "Medium" | "Hard";

export interface VocabWord {
  id: string;
  word: string;
  definition: string;
  example: string;
  wordParts?: string;
  difficulty: VocabDifficulty;
}

export const VOCAB: VocabWord[] = [
  { id: "abate", word: "Abate", difficulty: "Medium",
    definition: "To become less intense or widespread; to reduce in amount or degree.",
    example: "The storm finally abated, and the exhausted crew stepped onto the calm deck.",
    wordParts: "From Old French 'abatre' — to beat down." },
  { id: "aberration", word: "Aberration", difficulty: "Hard",
    definition: "A departure from what is normal, usual, or expected; an anomaly.",
    example: "A single warm week in January was an aberration, not a sign of a changing season.",
    wordParts: "Latin 'ab-' (away) + 'errare' (to wander) — a wandering away from the norm." },
  { id: "abstain", word: "Abstain", difficulty: "Medium",
    definition: "To choose not to do or have something, especially by deliberate choice.",
    example: "She abstained from commenting until she had read every page of the report.",
    wordParts: "Latin 'abs-' (from) + 'tenere' (to hold) — to hold back from." },
  { id: "abstruse", word: "Abstruse", difficulty: "Hard",
    definition: "Difficult to understand; obscure and hard to follow.",
    example: "The lecture grew so abstruse that even the graduate students stopped taking notes.",
    wordParts: "Latin 'abs-' (away) + 'trudere' (to push) — pushed away from easy understanding." },
  { id: "adroit", word: "Adroit", difficulty: "Hard",
    definition: "Clever or skillful in using the hands or mind.",
    example: "An adroit negotiator, he turned an angry room into a signed agreement within an hour.",
    wordParts: "French 'à droit' — according to right, i.e. done properly." },
  { id: "ambivalent", word: "Ambivalent", difficulty: "Medium",
    definition: "Having mixed or contradictory feelings about something.",
    example: "He was ambivalent about the promotion, proud of the title yet wary of the hours.",
    wordParts: "Latin 'ambi-' (both) + 'valere' (to be strong) — pulled strongly both ways." },
  { id: "ameliorate", word: "Ameliorate", difficulty: "Hard",
    definition: "To make a bad or unsatisfactory situation better.",
    example: "Small policy changes did little to ameliorate the shortage of affordable housing.",
    wordParts: "Latin 'melior' (better) — to make better." },
  { id: "anomaly", word: "Anomaly", difficulty: "Medium",
    definition: "Something that deviates from what is standard, normal, or expected.",
    example: "The sensor reading was an anomaly the engineers could not immediately explain.",
    wordParts: "Greek 'an-' (not) + 'homalos' (even) — not even, irregular." },
  { id: "antipathy", word: "Antipathy", difficulty: "Hard",
    definition: "A deep-seated feeling of dislike; strong aversion.",
    example: "Her antipathy toward crowded rooms kept her away from the celebration.",
    wordParts: "Greek 'anti-' (against) + 'pathos' (feeling) — feeling against." },
  { id: "arduous", word: "Arduous", difficulty: "Medium",
    definition: "Requiring great effort; difficult and tiring.",
    example: "The arduous climb took two days, but the view from the summit justified every step.",
    wordParts: "Latin 'arduus' — steep, high." },
  { id: "assiduous", word: "Assiduous", difficulty: "Hard",
    definition: "Showing great care, attention, and persistent effort.",
    example: "Through assiduous practice, she transformed a shaky essay into a polished argument.",
    wordParts: "Latin 'assidere' (to sit at) — sitting steadily at a task." },
  { id: "audacious", word: "Audacious", difficulty: "Medium",
    definition: "Showing a willingness to take bold risks; daring.",
    example: "The startup's audacious plan to rebuild the city's transit was met with skepticism.",
    wordParts: "Latin 'audax' (bold), from 'audere' (to dare)." },
  { id: "benevolent", word: "Benevolent", difficulty: "Medium",
    definition: "Well-meaning and kindly; showing goodwill.",
    example: "A benevolent stranger paid for the family's groceries and quietly left the store.",
    wordParts: "Latin 'bene' (well) + 'velle' (to wish) — wishing well." },
  { id: "candor", word: "Candor", difficulty: "Medium",
    definition: "The quality of being open, honest, and sincere in speech.",
    example: "The scientist answered with rare candor, admitting the limits of her own data.",
    wordParts: "Latin 'candere' (to shine, be white) — clear, unclouded honesty." },
  { id: "capricious", word: "Capricious", difficulty: "Hard",
    definition: "Given to sudden and unpredictable changes of mood or behavior.",
    example: "The capricious weather ruined the picnic, shifting from sun to hail within minutes.",
    wordParts: "Italian 'capriccio' — a sudden whim." },
  { id: "circumspect", word: "Circumspect", difficulty: "Hard",
    definition: "Cautious and careful; wary of risks before acting.",
    example: "A circumspect investor, she studied every filing before committing a single dollar.",
    wordParts: "Latin 'circum-' (around) + 'spicere' (to look) — looking around before acting." },
  { id: "cogent", word: "Cogent", difficulty: "Hard",
    definition: "Clear, logical, and convincing.",
    example: "His cogent argument left even his opponents nodding in reluctant agreement.",
    wordParts: "Latin 'cogere' (to drive together) — a case that compels belief." },
  { id: "concise", word: "Concise", difficulty: "Easy",
    definition: "Giving a lot of information clearly and in a few words; brief but complete.",
    example: "The editor asked for a concise summary — three sentences, not three pages.",
    wordParts: "Latin 'concidere' (to cut up) — cut down to essentials." },
  { id: "conspicuous", word: "Conspicuous", difficulty: "Medium",
    definition: "Clearly visible; attracting notice or attention.",
    example: "Her bright coat made her conspicuous in the sea of gray commuters.",
    wordParts: "Latin 'con-' (intensive) + 'spicere' (to look) — very much seen." },
  { id: "deft", word: "Deft", difficulty: "Medium",
    definition: "Neatly skillful and quick in movement or action.",
    example: "With a deft flick of the wrist, the chef folded the omelet perfectly.",
    wordParts: "Related to Old English 'gedæfte' — gentle, apt." },
  { id: "deride", word: "Deride", difficulty: "Hard",
    definition: "To express contempt for; to mock or ridicule.",
    example: "Critics derided the film at first, though audiences soon proved them wrong.",
    wordParts: "Latin 'de-' (down) + 'ridere' (to laugh) — to laugh down at." },
  { id: "diligent", word: "Diligent", difficulty: "Easy",
    definition: "Showing careful and persistent effort in work or duties.",
    example: "A diligent student, he reviewed each chapter twice before the exam.",
    wordParts: "Latin 'diligere' (to value, take delight in) — attentive care." },
  { id: "disdain", word: "Disdain", difficulty: "Medium",
    definition: "The feeling that someone or something deserves contempt; scorn.",
    example: "She looked at the sloppy work with open disdain and handed it back.",
    wordParts: "Latin 'dis-' (not) + 'dignari' (to deem worthy) — to deem unworthy." },
  { id: "eloquent", word: "Eloquent", difficulty: "Medium",
    definition: "Fluent, persuasive, and moving in speech or writing.",
    example: "His eloquent tribute brought the entire hall to a respectful silence.",
    wordParts: "Latin 'e-' (out) + 'loqui' (to speak) — to speak out well." },
  { id: "enervate", word: "Enervate", difficulty: "Hard",
    definition: "To drain of energy or vitality; to weaken.",
    example: "The relentless heat enervated the hikers long before they reached the shade.",
    wordParts: "Latin 'e-' (out) + 'nervus' (sinew) — to take the sinew out of." },
  { id: "ephemeral", word: "Ephemeral", difficulty: "Hard",
    definition: "Lasting for a very short time; fleeting.",
    example: "The beauty of the cherry blossoms is ephemeral, gone within a single week.",
    wordParts: "Greek 'epi-' (on) + 'hemera' (day) — lasting only a day." },
  { id: "equivocal", word: "Equivocal", difficulty: "Hard",
    definition: "Open to more than one interpretation; ambiguous or deliberately unclear.",
    example: "The official gave an equivocal answer that neither confirmed nor denied the plan.",
    wordParts: "Latin 'aequus' (equal) + 'vox' (voice) — of equal, competing meanings." },
  { id: "fastidious", word: "Fastidious", difficulty: "Hard",
    definition: "Very attentive to detail; hard to please and concerned with accuracy.",
    example: "A fastidious editor, she flagged every misplaced comma in the manuscript.",
    wordParts: "Latin 'fastidium' — loathing, squeamishness." },
  { id: "frugal", word: "Frugal", difficulty: "Easy",
    definition: "Sparing or economical with money or resources.",
    example: "Their frugal habits let the family save enough for a home in just five years.",
    wordParts: "Latin 'frugalis' — thrifty, useful." },
  { id: "garrulous", word: "Garrulous", difficulty: "Hard",
    definition: "Excessively talkative, especially about trivial matters.",
    example: "The garrulous passenger narrated his entire life story before the plane even took off.",
    wordParts: "Latin 'garrire' (to chatter)." },
  { id: "gregarious", word: "Gregarious", difficulty: "Medium",
    definition: "Fond of company; sociable and outgoing.",
    example: "Gregarious by nature, she knew half the room within minutes of arriving.",
    wordParts: "Latin 'grex' (flock, herd) — inclined to gather in a group." },
  { id: "impede", word: "Impede", difficulty: "Medium",
    definition: "To obstruct or slow the progress of something.",
    example: "Fallen branches impeded the rescue team's path through the forest.",
    wordParts: "Latin 'in-' (in) + 'pes' (foot) — to catch by the foot, entangle." },
  { id: "inevitable", word: "Inevitable", difficulty: "Easy",
    definition: "Certain to happen; unable to be avoided or prevented.",
    example: "Given the evidence, the jury's verdict felt inevitable long before it was read.",
    wordParts: "Latin 'in-' (not) + 'evitare' (to avoid) — not avoidable." },
  { id: "lucid", word: "Lucid", difficulty: "Medium",
    definition: "Expressed clearly and easy to understand; also, clear-minded.",
    example: "Her lucid explanation turned a tangle of equations into an obvious idea.",
    wordParts: "Latin 'lucidus' (bright), from 'lux' (light)." },
  { id: "meticulous", word: "Meticulous", difficulty: "Medium",
    definition: "Showing great attention to detail; very careful and precise.",
    example: "The watchmaker's meticulous work meant no gear was ever out of place.",
    wordParts: "Latin 'metus' (fear) — originally 'fearful', now painstakingly careful." },
  { id: "mitigate", word: "Mitigate", difficulty: "Medium",
    definition: "To make less severe, serious, or painful.",
    example: "Planting trees along the river helped mitigate the damage from seasonal floods.",
    wordParts: "Latin 'mitis' (soft) + 'agere' (to make) — to make milder." },
  { id: "nonchalant", word: "Nonchalant", difficulty: "Medium",
    definition: "Appearing casually calm and relaxed; not showing worry or interest.",
    example: "He gave a nonchalant shrug, as if losing the match meant nothing at all.",
    wordParts: "French 'non' (not) + 'chaloir' (to matter) — as if it does not matter." },
  { id: "obscure", word: "Obscure", difficulty: "Medium",
    definition: "Not clearly understood or expressed; also, to hide or make unclear.",
    example: "The poem's meaning stayed obscure until she learned the poet's private history.",
    wordParts: "Latin 'obscurus' — dark, covered over." },
  { id: "ostentatious", word: "Ostentatious", difficulty: "Hard",
    definition: "Designed to impress or attract notice; showy in a vulgar way.",
    example: "The mansion's ostentatious gold gates drew stares from every passing car.",
    wordParts: "Latin 'ostentare' (to display) — making a display." },
  { id: "placate", word: "Placate", difficulty: "Medium",
    definition: "To make someone less angry or hostile; to soothe.",
    example: "A sincere apology did more to placate the customer than any refund could.",
    wordParts: "Latin 'placare' (to calm, appease)." },
  { id: "pragmatic", word: "Pragmatic", difficulty: "Medium",
    definition: "Dealing with things sensibly and realistically rather than idealistically.",
    example: "Her pragmatic plan ignored grand theories and focused on what could ship this month.",
    wordParts: "Greek 'pragma' (deed, action) — focused on practical action." },
  { id: "prudent", word: "Prudent", difficulty: "Medium",
    definition: "Acting with care and thought for the future; sensibly cautious.",
    example: "It was prudent to save for emergencies, and the fund soon proved its worth.",
    wordParts: "Latin 'providens' (foreseeing) — looking ahead wisely." },
  { id: "reticent", word: "Reticent", difficulty: "Hard",
    definition: "Not revealing one's thoughts readily; reserved and quiet.",
    example: "Usually reticent, the witness surprised the court by speaking at length.",
    wordParts: "Latin 're-' (again) + 'tacere' (to be silent) — inclined to silence." },
  { id: "scrutinize", word: "Scrutinize", difficulty: "Medium",
    definition: "To examine or inspect closely and thoroughly.",
    example: "Auditors scrutinized every receipt before signing off on the budget.",
    wordParts: "Latin 'scrutari' (to search) — originally to sort through rags." },
  { id: "spurious", word: "Spurious", difficulty: "Hard",
    definition: "Not genuine, authentic, or true; falsely appearing to be real.",
    example: "The article was pulled once editors found its statistics were spurious.",
    wordParts: "Latin 'spurius' — false, illegitimate." },
  { id: "tenuous", word: "Tenuous", difficulty: "Hard",
    definition: "Very weak or slight; lacking a sound basis.",
    example: "The theory rested on tenuous evidence that collapsed under a single new study.",
    wordParts: "Latin 'tenuis' — thin, slender." },
  { id: "ubiquitous", word: "Ubiquitous", difficulty: "Hard",
    definition: "Present, appearing, or found everywhere at once.",
    example: "Smartphones have become so ubiquitous that a quiet room is now a rarity.",
    wordParts: "Latin 'ubique' (everywhere)." },
  { id: "vivacious", word: "Vivacious", difficulty: "Medium",
    definition: "Attractively lively and animated; full of energy and enthusiasm.",
    example: "Her vivacious storytelling kept the whole table laughing well past midnight.",
    wordParts: "Latin 'vivax' (lively), from 'vivere' (to live)." },

  { id: "abhor", word: "Abhor", difficulty: "Medium",
    definition: "To regard with disgust and hatred; to detest utterly.",
    example: "She abhorred cruelty of any kind and left the room whenever it appeared on screen.",
    wordParts: "Latin 'ab-' (away) + 'horrere' (to shudder) — to shrink away in horror." },
  { id: "abridge", word: "Abridge", difficulty: "Medium",
    definition: "To shorten a text or piece of work while keeping the main content.",
    example: "The publisher abridged the 900-page novel into a slim edition for younger readers.",
    wordParts: "Latin 'abbreviare' — to shorten." },
  { id: "abscond", word: "Abscond", difficulty: "Hard",
    definition: "To leave hurriedly and secretly, typically to avoid capture.",
    example: "The cashier absconded with the weekend's earnings before anyone noticed.",
    wordParts: "Latin 'abs-' (away) + 'condere' (to hide) — to hide oneself away." },
  { id: "abstemious", word: "Abstemious", difficulty: "Hard",
    definition: "Sparing or moderate, especially in eating and drinking.",
    example: "His abstemious diet of plain rice and vegetables surprised his lavish dinner guests.",
    wordParts: "Latin 'abs-' (from) + 'temetum' (strong drink) — holding back from indulgence." },
  { id: "acumen", word: "Acumen", difficulty: "Hard",
    definition: "The ability to make good judgments and quick decisions; keen insight.",
    example: "Her business acumen turned a small stall into a chain of stores within five years.",
    wordParts: "Latin 'acumen' (a point), from 'acuere' (to sharpen)." },
  { id: "admonish", word: "Admonish", difficulty: "Medium",
    definition: "To warn or reprimand someone firmly but not harshly.",
    example: "The coach admonished the players for skipping warm-ups before the match.",
    wordParts: "Latin 'ad-' (to) + 'monere' (to warn)." },
  { id: "adverse", word: "Adverse", difficulty: "Easy",
    definition: "Unfavorable, harmful, or acting against one's interests.",
    example: "The medicine worked, though a few patients reported adverse side effects.",
    wordParts: "Latin 'ad-' (toward) + 'vertere' (to turn) — turned against." },
  { id: "aesthetic", word: "Aesthetic", difficulty: "Medium",
    definition: "Concerned with beauty or the appreciation of art and appearance.",
    example: "The architect valued aesthetic harmony as much as structural strength.",
    wordParts: "Greek 'aisthetikos' — of sense perception." },
  { id: "affable", word: "Affable", difficulty: "Medium",
    definition: "Friendly, good-natured, and easy to talk to.",
    example: "Their affable host made even the shyest guest feel instantly at home.",
    wordParts: "Latin 'affari' (to speak to) — approachable in conversation." },
  { id: "alacrity", word: "Alacrity", difficulty: "Hard",
    definition: "Brisk and cheerful readiness; eager willingness.",
    example: "She accepted the challenge with such alacrity that her boss barely finished asking.",
    wordParts: "Latin 'alacer' (lively, eager)." },
  { id: "alleviate", word: "Alleviate", difficulty: "Medium",
    definition: "To make suffering or a problem less severe.",
    example: "A cool breeze did little to alleviate the crushing afternoon heat.",
    wordParts: "Latin 'ad-' (to) + 'levis' (light) — to lighten." },
  { id: "aloof", word: "Aloof", difficulty: "Medium",
    definition: "Distant, cool, and uninvolved; not friendly or forthcoming.",
    example: "He stayed aloof at the party, watching the crowd from a quiet corner.",
    wordParts: "Originally a nautical term — to keep the ship's head to the wind, i.e. away." },
  { id: "altruistic", word: "Altruistic", difficulty: "Medium",
    definition: "Showing selfless concern for the well-being of others.",
    example: "Her altruistic work at the shelter earned nothing but the gratitude of strangers.",
    wordParts: "Latin 'alter' (other) — regard for others." },
  { id: "ambiguous", word: "Ambiguous", difficulty: "Medium",
    definition: "Open to more than one interpretation; unclear or vague.",
    example: "The instructions were so ambiguous that no two students built the same model.",
    wordParts: "Latin 'ambi-' (both) + 'agere' (to drive) — leading two ways." },
  { id: "amenable", word: "Amenable", difficulty: "Medium",
    definition: "Willing to cooperate or be persuaded; open to suggestion.",
    example: "The manager was amenable to new ideas, so the team proposed a bold redesign.",
    wordParts: "Latin 'minari' (to threaten, drive) via French — able to be led." },
  { id: "amiable", word: "Amiable", difficulty: "Easy",
    definition: "Having a friendly and pleasant manner.",
    example: "An amiable smile put the nervous interviewee at ease within seconds.",
    wordParts: "Latin 'amicabilis' (friendly), from 'amicus' (friend)." },
  { id: "anachronism", word: "Anachronism", difficulty: "Hard",
    definition: "Something placed in the wrong historical period; out of its time.",
    example: "The knight's wristwatch was a glaring anachronism in the medieval film.",
    wordParts: "Greek 'ana-' (against) + 'chronos' (time) — against the times." },
  { id: "apathy", word: "Apathy", difficulty: "Medium",
    definition: "A lack of interest, enthusiasm, or concern.",
    example: "Voter apathy left the town hall nearly empty on election night.",
    wordParts: "Greek 'a-' (without) + 'pathos' (feeling)." },
  { id: "appease", word: "Appease", difficulty: "Medium",
    definition: "To pacify or calm someone by giving in to demands.",
    example: "They lowered the price to appease the frustrated customer.",
    wordParts: "Latin 'ad-' (to) + 'pax' (peace) — to bring to peace." },
  { id: "apprehensive", word: "Apprehensive", difficulty: "Medium",
    definition: "Anxious or fearful that something bad will happen.",
    example: "She felt apprehensive about the results, though she had studied for weeks.",
    wordParts: "Latin 'apprehendere' (to grasp) — grasping at fears of what may come." },
  { id: "arbitrary", word: "Arbitrary", difficulty: "Medium",
    definition: "Based on random choice or personal whim rather than reason.",
    example: "The seating was arbitrary, decided by whoever arrived first.",
    wordParts: "Latin 'arbiter' (judge) — left to a judge's discretion." },
  { id: "archaic", word: "Archaic", difficulty: "Medium",
    definition: "Very old-fashioned or belonging to an earlier period.",
    example: "The contract used archaic language that no modern lawyer would write.",
    wordParts: "Greek 'archaios' (ancient), from 'arche' (beginning)." },
  { id: "articulate", word: "Articulate", difficulty: "Medium",
    definition: "Able to express thoughts clearly and fluently.",
    example: "The articulate spokesperson answered every question without a single stumble.",
    wordParts: "Latin 'articulare' (to divide into joints) — to speak in distinct parts." },
  { id: "ascetic", word: "Ascetic", difficulty: "Hard",
    definition: "Practicing severe self-discipline and abstaining from pleasures.",
    example: "The monk lived an ascetic life, owning nothing but a robe and a bowl.",
    wordParts: "Greek 'asketes' (one who practices), from 'askein' (to exercise)." },
  { id: "assuage", word: "Assuage", difficulty: "Hard",
    definition: "To ease or lessen an unpleasant feeling; to soothe.",
    example: "A warm apology assuaged her anger far more than any gift could have.",
    wordParts: "Latin 'ad-' (to) + 'suavis' (sweet) — to sweeten, calm." },
  { id: "astute", word: "Astute", difficulty: "Medium",
    definition: "Having sharp judgment; shrewd and perceptive.",
    example: "An astute observer, she noticed the flaw everyone else had missed.",
    wordParts: "Latin 'astutus' (crafty), from 'astus' (skill)." },
  { id: "augment", word: "Augment", difficulty: "Medium",
    definition: "To make something greater by adding to it.",
    example: "He augmented his income by tutoring on weekends.",
    wordParts: "Latin 'augere' (to increase)." },
  { id: "austere", word: "Austere", difficulty: "Hard",
    definition: "Severe or strict in manner; plain and without comfort or luxury.",
    example: "The austere classroom held nothing but wooden benches and a single chalkboard.",
    wordParts: "Greek 'austeros' (harsh, bitter)." },
  { id: "avarice", word: "Avarice", difficulty: "Hard",
    definition: "Extreme greed for wealth or material gain.",
    example: "His avarice grew with every deal, yet he never seemed content.",
    wordParts: "Latin 'avarus' (greedy), from 'avere' (to crave)." },
  { id: "aversion", word: "Aversion", difficulty: "Medium",
    definition: "A strong dislike or unwillingness toward something.",
    example: "Her aversion to spiders sent her sprinting from the garden shed.",
    wordParts: "Latin 'a-' (from) + 'vertere' (to turn) — a turning away." },
  { id: "banal", word: "Banal", difficulty: "Hard",
    definition: "So lacking in originality as to be boring; predictable.",
    example: "The speech was full of banal advice everyone had heard a hundred times.",
    wordParts: "French 'banal' — common to all, ordinary." },
  { id: "belie", word: "Belie", difficulty: "Hard",
    definition: "To give a false impression of; to contradict.",
    example: "Her calm voice belied the panic she felt inside.",
    wordParts: "Old English 'beleogan' (to deceive by lying)." },
  { id: "belligerent", word: "Belligerent", difficulty: "Medium",
    definition: "Hostile and aggressive; eager to fight.",
    example: "The belligerent customer demanded a refund before even opening the box.",
    wordParts: "Latin 'bellum' (war) + 'gerere' (to wage)." },
  { id: "benign", word: "Benign", difficulty: "Medium",
    definition: "Gentle and harmless; kindly in effect.",
    example: "The tumor was benign, and the relief in the room was immediate.",
    wordParts: "Latin 'benignus' (kind), from 'bene' (well)." },
  { id: "bolster", word: "Bolster", difficulty: "Medium",
    definition: "To support, strengthen, or reinforce.",
    example: "New evidence bolstered the lawyer's already strong case.",
    wordParts: "Old English 'bolster' (a cushion) — something that props up." },
  { id: "brevity", word: "Brevity", difficulty: "Medium",
    definition: "Shortness of time or expression; conciseness.",
    example: "The judge praised the lawyer for the brevity of her closing argument.",
    wordParts: "Latin 'brevis' (short)." },
  { id: "brusque", word: "Brusque", difficulty: "Hard",
    definition: "Abrupt or curt in manner; blunt to the point of rudeness.",
    example: "His brusque reply ended the conversation before it began.",
    wordParts: "Italian 'brusco' (sharp, tart)." },
  { id: "cacophony", word: "Cacophony", difficulty: "Hard",
    definition: "A harsh, jarring mixture of sounds.",
    example: "A cacophony of horns and sirens rose from the gridlocked street.",
    wordParts: "Greek 'kakos' (bad) + 'phone' (sound)." },
  { id: "cajole", word: "Cajole", difficulty: "Hard",
    definition: "To persuade someone by flattery or gentle coaxing.",
    example: "She cajoled her brother into covering her shift with promises of free lunch.",
    wordParts: "French 'cajoler' (to coax, wheedle)." },
  { id: "callous", word: "Callous", difficulty: "Medium",
    definition: "Showing an insensitive and cruel disregard for others.",
    example: "His callous remark about the layoffs stunned the entire office.",
    wordParts: "Latin 'callosus' (hardened, thick-skinned)." },
  { id: "candid", word: "Candid", difficulty: "Medium",
    definition: "Truthful and straightforward; frank.",
    example: "In a candid interview, the coach admitted the team was unprepared.",
    wordParts: "Latin 'candidus' (white, clear) — clear and open." },
  { id: "catalyst", word: "Catalyst", difficulty: "Medium",
    definition: "A person or thing that causes an event or speeds up change.",
    example: "The protest became the catalyst for sweeping reforms across the city.",
    wordParts: "Greek 'kata-' (down) + 'lyein' (to loosen)." },
  { id: "caustic", word: "Caustic", difficulty: "Hard",
    definition: "Sarcastic and cutting; also, capable of burning by chemical action.",
    example: "Her caustic wit could silence a room in a single sentence.",
    wordParts: "Greek 'kaustikos' (burning), from 'kaiein' (to burn)." },
  { id: "censure", word: "Censure", difficulty: "Hard",
    definition: "To express strong, formal disapproval of someone or something.",
    example: "The committee voted to censure the official for misusing public funds.",
    wordParts: "Latin 'censere' (to assess, judge)." },
  { id: "clandestine", word: "Clandestine", difficulty: "Hard",
    definition: "Kept secret, especially because it is illicit or improper.",
    example: "Their clandestine meetings took place after midnight in an empty warehouse.",
    wordParts: "Latin 'clam' (secretly)." },
  { id: "coerce", word: "Coerce", difficulty: "Medium",
    definition: "To force someone to do something by threats or pressure.",
    example: "No one should be coerced into signing a contract they don't understand.",
    wordParts: "Latin 'co-' (together) + 'arcere' (to restrain)." },
  { id: "complacent", word: "Complacent", difficulty: "Medium",
    definition: "Smugly satisfied with oneself and unaware of possible dangers.",
    example: "After an early lead, the team grew complacent and lost in the final minutes.",
    wordParts: "Latin 'complacere' (to please greatly)." },
  { id: "condone", word: "Condone", difficulty: "Medium",
    definition: "To accept or overlook behavior that is wrong.",
    example: "The school does not condone cheating, whatever the excuse.",
    wordParts: "Latin 'condonare' (to forgive, give up)." },
  { id: "condescend", word: "Condescend", difficulty: "Medium",
    definition: "To behave as if superior; to talk down to others.",
    example: "The expert never condescended, explaining ideas as if to a respected equal.",
    wordParts: "Latin 'con-' + 'descendere' (to come down)." },
  { id: "connoisseur", word: "Connoisseur", difficulty: "Hard",
    definition: "An expert judge in matters of taste, especially the fine arts.",
    example: "A connoisseur of tea, she could name the region from a single sip.",
    wordParts: "French 'connoisseur', from Latin 'cognoscere' (to know)." },
  { id: "contrite", word: "Contrite", difficulty: "Hard",
    definition: "Feeling or showing sincere regret for wrongdoing.",
    example: "His contrite apology, offered with lowered eyes, won back their trust.",
    wordParts: "Latin 'conterere' (to grind down) — worn down by guilt." },
  { id: "conundrum", word: "Conundrum", difficulty: "Medium",
    definition: "A confusing and difficult problem or question.",
    example: "How to fund the new library without raising taxes was a real conundrum.",
    wordParts: "Origin uncertain — a mock-Latin term from the 1500s." },
  { id: "copious", word: "Copious", difficulty: "Medium",
    definition: "Abundant in supply or quantity; plentiful.",
    example: "She took copious notes, filling three notebooks by the end of the term.",
    wordParts: "Latin 'copia' (plenty)." },
  { id: "corroborate", word: "Corroborate", difficulty: "Hard",
    definition: "To confirm or support a statement with evidence.",
    example: "Two witnesses corroborated the driver's account of the accident.",
    wordParts: "Latin 'con-' + 'roborare' (to strengthen), from 'robur' (strength)." },
  { id: "credible", word: "Credible", difficulty: "Easy",
    definition: "Able to be believed; convincing and trustworthy.",
    example: "Without a credible source, the reporter refused to run the story.",
    wordParts: "Latin 'credere' (to believe)." },
  { id: "cryptic", word: "Cryptic", difficulty: "Medium",
    definition: "Mysterious or obscure in meaning; deliberately puzzling.",
    example: "His cryptic note read only, 'Look where the light never reaches.'",
    wordParts: "Greek 'kryptos' (hidden)." },
  { id: "culpable", word: "Culpable", difficulty: "Hard",
    definition: "Deserving blame; responsible for a fault or wrong.",
    example: "The report found the manager culpable for ignoring the safety warnings.",
    wordParts: "Latin 'culpa' (fault, blame)." },
  { id: "cursory", word: "Cursory", difficulty: "Hard",
    definition: "Hasty and superficial; done without attention to detail.",
    example: "A cursory glance at the contract missed the clause that cost them thousands.",
    wordParts: "Latin 'cursor' (runner), from 'currere' (to run)." },
  { id: "daunt", word: "Daunt", difficulty: "Medium",
    definition: "To make someone feel intimidated or discouraged.",
    example: "The steep syllabus daunted the freshmen on their very first day.",
    wordParts: "Latin 'domitare' (to tame, subdue)." },
  { id: "debunk", word: "Debunk", difficulty: "Medium",
    definition: "To expose the falseness of a belief or claim.",
    example: "The scientist debunked the myth with a simple, repeatable experiment.",
    wordParts: "English 'de-' (remove) + 'bunk' (nonsense)." },
  { id: "decorum", word: "Decorum", difficulty: "Hard",
    definition: "Behavior that is polite and appropriate to a situation.",
    example: "Despite the heated debate, the senators maintained a strict decorum.",
    wordParts: "Latin 'decorus' (fitting, proper)." },
  { id: "deferential", word: "Deferential", difficulty: "Hard",
    definition: "Showing respectful submission or regard for another.",
    example: "The new intern was deferential to senior staff, quick to listen and slow to argue.",
    wordParts: "Latin 'deferre' (to carry down, yield)." },
  { id: "delineate", word: "Delineate", difficulty: "Hard",
    definition: "To describe or outline something precisely.",
    example: "The manual clearly delineates each step of the assembly process.",
    wordParts: "Latin 'de-' + 'lineare' (to draw lines)." },
  { id: "denounce", word: "Denounce", difficulty: "Medium",
    definition: "To publicly condemn someone or something as wrong.",
    example: "Leaders around the world denounced the attack within hours.",
    wordParts: "Latin 'de-' + 'nuntiare' (to announce)." },
  { id: "deplete", word: "Deplete", difficulty: "Medium",
    definition: "To use up or reduce the amount of something.",
    example: "The long drought depleted the reservoir to a fraction of its usual level.",
    wordParts: "Latin 'deplere' (to empty out)." },
  { id: "deplore", word: "Deplore", difficulty: "Medium",
    definition: "To strongly disapprove of and regret something.",
    example: "Critics deplored the decision to demolish the historic theater.",
    wordParts: "Latin 'deplorare' (to weep bitterly)." },
  { id: "despondent", word: "Despondent", difficulty: "Hard",
    definition: "In low spirits from loss of hope or courage.",
    example: "After the third rejection letter, she grew despondent about her chances.",
    wordParts: "Latin 'despondere' (to give up, lose heart)." },
  { id: "deter", word: "Deter", difficulty: "Medium",
    definition: "To discourage someone from acting by instilling doubt or fear.",
    example: "Heavy fines are meant to deter drivers from speeding through school zones.",
    wordParts: "Latin 'de-' + 'terrere' (to frighten)." },
  { id: "detrimental", word: "Detrimental", difficulty: "Medium",
    definition: "Tending to cause harm or damage.",
    example: "Skipping sleep before an exam is detrimental to both memory and mood.",
    wordParts: "Latin 'detrimentum' (loss, damage)." },
  { id: "diatribe", word: "Diatribe", difficulty: "Hard",
    definition: "A forceful and bitter verbal attack against someone or something.",
    example: "His after-dinner diatribe against modern music emptied the room.",
    wordParts: "Greek 'diatribe' (a wearing away, discourse)." },
  { id: "didactic", word: "Didactic", difficulty: "Hard",
    definition: "Intended to teach, often with a moral lesson.",
    example: "The fable was openly didactic, ending with a tidy lesson about honesty.",
    wordParts: "Greek 'didaktikos' (apt at teaching)." },
  { id: "diffident", word: "Diffident", difficulty: "Hard",
    definition: "Shy and lacking self-confidence.",
    example: "Too diffident to raise his hand, he kept the right answer to himself.",
    wordParts: "Latin 'diffidere' (to distrust) — distrusting oneself." },
  { id: "digress", word: "Digress", difficulty: "Medium",
    definition: "To wander away from the main subject in speech or writing.",
    example: "The professor digressed into a long story and never returned to the topic.",
    wordParts: "Latin 'dis-' (apart) + 'gradi' (to step)." },
  { id: "disparage", word: "Disparage", difficulty: "Hard",
    definition: "To speak of someone or something as unimportant; to belittle.",
    example: "It is easy to disparage a plan you were too timid to propose yourself.",
    wordParts: "Old French 'desparagier' (to marry below one's rank)." },
  { id: "disparate", word: "Disparate", difficulty: "Hard",
    definition: "Essentially different in kind; not comparable.",
    example: "The exhibit somehow united disparate styles into one striking whole.",
    wordParts: "Latin 'disparatus' (separated), from 'dis-' + 'parare'." },
  { id: "dissent", word: "Dissent", difficulty: "Medium",
    definition: "To hold or express opinions that differ from those officially held.",
    example: "One judge dissented, arguing the ruling ignored decades of precedent.",
    wordParts: "Latin 'dis-' (apart) + 'sentire' (to feel)." },
  { id: "dogmatic", word: "Dogmatic", difficulty: "Hard",
    definition: "Asserting opinions as if they were undeniable facts.",
    example: "His dogmatic tone left no room for questions or fresh evidence.",
    wordParts: "Greek 'dogma' (opinion, belief)." },
  { id: "dubious", word: "Dubious", difficulty: "Medium",
    definition: "Hesitating or doubtful; also, questionable or suspect.",
    example: "She was dubious about the deal that promised huge returns overnight.",
    wordParts: "Latin 'dubius' (wavering, doubtful)." },
  { id: "ebullient", word: "Ebullient", difficulty: "Hard",
    definition: "Cheerful and full of energy; overflowing with excitement.",
    example: "The ebullient crowd sang all the way home after the victory.",
    wordParts: "Latin 'ebullire' (to boil up)." },
  { id: "eclectic", word: "Eclectic", difficulty: "Medium",
    definition: "Drawing from a wide and diverse range of sources or styles.",
    example: "Her eclectic playlist jumped from opera to hip-hop without apology.",
    wordParts: "Greek 'eklektikos' (selective), from 'eklegein' (to pick out)." },
  { id: "egregious", word: "Egregious", difficulty: "Hard",
    definition: "Outstandingly bad; shocking in a conspicuous way.",
    example: "The report contained an egregious error that changed the entire conclusion.",
    wordParts: "Latin 'ex-' (out) + 'grex' (flock) — standing out from the herd." },
  { id: "elicit", word: "Elicit", difficulty: "Medium",
    definition: "To draw out a response, answer, or reaction from someone.",
    example: "A single gentle question elicited the whole story from the frightened child.",
    wordParts: "Latin 'elicere' (to draw out)." },
  { id: "embellish", word: "Embellish", difficulty: "Medium",
    definition: "To make more attractive by adding detail; also, to exaggerate.",
    example: "He embellished the tale with a dragon that had never appeared in the original.",
    wordParts: "Old French 'embellir' (to make beautiful)." },
  { id: "empirical", word: "Empirical", difficulty: "Hard",
    definition: "Based on observation or experiment rather than theory.",
    example: "The claim needed empirical support, not just a persuasive argument.",
    wordParts: "Greek 'empeirikos' (experienced), from 'peira' (trial)." },
  { id: "emulate", word: "Emulate", difficulty: "Medium",
    definition: "To imitate someone admired in order to match or surpass them.",
    example: "Young writers often emulate the authors who first inspired them.",
    wordParts: "Latin 'aemulari' (to rival)." },
  { id: "endorse", word: "Endorse", difficulty: "Easy",
    definition: "To publicly declare approval or support for something.",
    example: "Three former champions endorsed the new training program.",
    wordParts: "Latin 'in-' + 'dorsum' (back) — originally to sign the back of a document." },
  { id: "enigma", word: "Enigma", difficulty: "Medium",
    definition: "A person or thing that is mysterious or hard to understand.",
    example: "Even to her closest friends, she remained something of an enigma.",
    wordParts: "Greek 'ainigma' (riddle)." },
  { id: "erudite", word: "Erudite", difficulty: "Hard",
    definition: "Having or showing deep, scholarly knowledge.",
    example: "The erudite lecture wove together history, art, and mathematics with ease.",
    wordParts: "Latin 'eruditus' (instructed), from 'e-' + 'rudis' (rough, untrained)." },
  { id: "esoteric", word: "Esoteric", difficulty: "Hard",
    definition: "Understood by only a small group with specialized knowledge.",
    example: "The paper was so esoteric that only a handful of specialists could follow it.",
    wordParts: "Greek 'esoterikos' (inner), from 'eso' (within)." },
  { id: "euphemism", word: "Euphemism", difficulty: "Medium",
    definition: "A mild word or phrase used in place of a harsh or blunt one.",
    example: "'Between jobs' is a common euphemism for being unemployed.",
    wordParts: "Greek 'eu-' (good) + 'pheme' (speech)." },
  { id: "exacerbate", word: "Exacerbate", difficulty: "Hard",
    definition: "To make a problem or bad situation worse.",
    example: "Shouting only exacerbated the tension already filling the room.",
    wordParts: "Latin 'ex-' + 'acerbus' (harsh, bitter)." },
  { id: "exonerate", word: "Exonerate", difficulty: "Hard",
    definition: "To clear someone of blame or a criminal charge.",
    example: "New DNA evidence exonerated the man after years behind bars.",
    wordParts: "Latin 'ex-' (off) + 'onus' (burden) — to remove a burden." },
  { id: "expedite", word: "Expedite", difficulty: "Medium",
    definition: "To make a process happen more quickly.",
    example: "Paying extra expedited the shipment so it arrived the next morning.",
    wordParts: "Latin 'expedire' (to free the feet, set in motion)." },
  { id: "extol", word: "Extol", difficulty: "Hard",
    definition: "To praise enthusiastically and highly.",
    example: "Reviewers extolled the novel as the finest of the decade.",
    wordParts: "Latin 'ex-' + 'tollere' (to raise)." },
  { id: "extraneous", word: "Extraneous", difficulty: "Hard",
    definition: "Irrelevant or unrelated to the matter at hand.",
    example: "The editor cut every extraneous detail until only the essential story remained.",
    wordParts: "Latin 'extraneus' (external), from 'extra' (outside)." },
  { id: "facilitate", word: "Facilitate", difficulty: "Medium",
    definition: "To make an action or process easier.",
    example: "A shared calendar facilitated planning across three time zones.",
    wordParts: "Latin 'facilis' (easy)." },
  { id: "fallacy", word: "Fallacy", difficulty: "Medium",
    definition: "A mistaken belief or a flaw in reasoning.",
    example: "It is a fallacy to assume that expensive always means better.",
    wordParts: "Latin 'fallere' (to deceive)." },
  { id: "fervent", word: "Fervent", difficulty: "Medium",
    definition: "Having or showing intense, passionate feeling.",
    example: "Her fervent belief in the cause kept the small group going for years.",
    wordParts: "Latin 'fervere' (to boil, glow)." },
  { id: "fickle", word: "Fickle", difficulty: "Medium",
    definition: "Changing frequently, especially in loyalties or affections.",
    example: "Fashion is fickle, adoring one color this year and mocking it the next.",
    wordParts: "Old English 'ficol' (deceitful, changeable)." },
  { id: "flagrant", word: "Flagrant", difficulty: "Hard",
    definition: "Conspicuously and outrageously bad or offensive.",
    example: "Running the red light in front of the officer was a flagrant violation.",
    wordParts: "Latin 'flagrare' (to blaze) — glaringly obvious." },
  { id: "flippant", word: "Flippant", difficulty: "Medium",
    definition: "Not showing a serious or respectful attitude.",
    example: "His flippant reply to the serious question annoyed the whole panel.",
    wordParts: "From 'flip' — nimble, glib in speech." },
  { id: "formidable", word: "Formidable", difficulty: "Medium",
    definition: "Inspiring fear or respect through being impressively large or capable.",
    example: "The champion faced a formidable opponent in the final round.",
    wordParts: "Latin 'formidare' (to fear)." },
  { id: "fortuitous", word: "Fortuitous", difficulty: "Hard",
    definition: "Happening by chance, often in a lucky way.",
    example: "A fortuitous meeting on the train led to a lifelong partnership.",
    wordParts: "Latin 'fortuitus' (happening by chance), from 'fors' (luck)." },
  { id: "futile", word: "Futile", difficulty: "Medium",
    definition: "Incapable of producing any useful result; pointless.",
    example: "Arguing with the storm was futile, so they simply took shelter.",
    wordParts: "Latin 'futilis' (leaky, worthless)." },
  { id: "galvanize", word: "Galvanize", difficulty: "Hard",
    definition: "To shock or excite someone into taking action.",
    example: "The speech galvanized the volunteers into knocking on every door in town.",
    wordParts: "Named after Luigi Galvani, who studied electric effects on muscles." },
  { id: "gaudy", word: "Gaudy", difficulty: "Medium",
    definition: "Extravagantly bright or showy in a tasteless way.",
    example: "The gaudy decorations clashed with the quiet elegance of the hall.",
    wordParts: "Possibly from Latin 'gaudium' (joy) via ornament." },
  { id: "grandiose", word: "Grandiose", difficulty: "Medium",
    definition: "Impressive or ambitious in a way that seems exaggerated.",
    example: "His grandiose plan to rebuild the whole city collapsed within a month.",
    wordParts: "Italian 'grandioso', from Latin 'grandis' (great)." },
  { id: "gratuitous", word: "Gratuitous", difficulty: "Hard",
    definition: "Uncalled for; done without good reason.",
    example: "The film's gratuitous violence added nothing to its thin story.",
    wordParts: "Latin 'gratuitus' (given freely, unearned)." },
  { id: "hackneyed", word: "Hackneyed", difficulty: "Hard",
    definition: "Overused and therefore lacking impact; clichéd.",
    example: "The poem leaned on hackneyed images of moons and roses.",
    wordParts: "From 'hackney', a horse hired out for ordinary use." },
  { id: "hamper", word: "Hamper", difficulty: "Medium",
    definition: "To hinder or impede the movement or progress of.",
    example: "Thick fog hampered the search well into the night.",
    wordParts: "Middle English 'hamperen' (to entangle)." },
  { id: "haughty", word: "Haughty", difficulty: "Medium",
    definition: "Arrogantly superior and disdainful toward others.",
    example: "The haughty critic dismissed the young chef without tasting a single dish.",
    wordParts: "Old French 'haut' (high), from Latin 'altus'." },
  { id: "iconoclast", word: "Iconoclast", difficulty: "Hard",
    definition: "A person who attacks cherished beliefs or established institutions.",
    example: "An iconoclast at heart, she questioned rules that everyone else obeyed.",
    wordParts: "Greek 'eikon' (image) + 'klan' (to break) — image-breaker." },
  { id: "idyllic", word: "Idyllic", difficulty: "Medium",
    definition: "Extremely happy, peaceful, or picturesque.",
    example: "They spent an idyllic afternoon by the lake, far from the noise of the city.",
    wordParts: "Greek 'eidyllion' (a short pastoral poem)." },
  { id: "impartial", word: "Impartial", difficulty: "Medium",
    definition: "Treating all sides equally; not favoring one over another.",
    example: "A judge must remain impartial, however strong her private opinions.",
    wordParts: "Latin 'in-' (not) + 'partialis' (biased)." },
  { id: "impetuous", word: "Impetuous", difficulty: "Hard",
    definition: "Acting quickly and without thought or care.",
    example: "His impetuous decision to quit left him with no plan and no income.",
    wordParts: "Latin 'impetus' (attack, impulse)." },
  { id: "implicit", word: "Implicit", difficulty: "Medium",
    definition: "Suggested or understood without being directly stated.",
    example: "There was an implicit agreement that no one would mention the mistake.",
    wordParts: "Latin 'implicitus' (entangled, folded in)." },
  { id: "inadvertent", word: "Inadvertent", difficulty: "Medium",
    definition: "Not resulting from deliberate intent; accidental.",
    example: "An inadvertent typo changed the meaning of the entire sentence.",
    wordParts: "Latin 'in-' (not) + 'advertere' (to turn the mind to)." },
  { id: "incessant", word: "Incessant", difficulty: "Medium",
    definition: "Continuing without pause or interruption.",
    example: "The incessant dripping of the faucet kept her awake all night.",
    wordParts: "Latin 'in-' (not) + 'cessare' (to cease)." },
  { id: "incisive", word: "Incisive", difficulty: "Hard",
    definition: "Sharp, clear, and direct in thought or expression.",
    example: "Her incisive question exposed the weakness at the heart of the plan.",
    wordParts: "Latin 'incidere' (to cut into)." },
  { id: "incite", word: "Incite", difficulty: "Medium",
    definition: "To stir up or provoke someone to action, often violent.",
    example: "The pamphlet was designed to incite the crowd to riot.",
    wordParts: "Latin 'in-' + 'citare' (to rouse)." },
  { id: "incongruous", word: "Incongruous", difficulty: "Hard",
    definition: "Out of place; not in harmony with its surroundings.",
    example: "The neon sign looked incongruous against the centuries-old stone church.",
    wordParts: "Latin 'in-' (not) + 'congruere' (to agree)." },
  { id: "indifferent", word: "Indifferent", difficulty: "Easy",
    definition: "Having no particular interest or concern; unmoved.",
    example: "He was indifferent to fashion, wearing the same gray coat for a decade.",
    wordParts: "Latin 'in-' (not) + 'differre' (to differ) — making no difference." },
  { id: "indignant", word: "Indignant", difficulty: "Medium",
    definition: "Feeling or showing anger at something unjust or unfair.",
    example: "She was indignant when told to pay for a mistake that wasn't hers.",
    wordParts: "Latin 'indignari' (to regard as unworthy)." },
  { id: "indolent", word: "Indolent", difficulty: "Hard",
    definition: "Wanting to avoid activity or effort; habitually lazy.",
    example: "The indolent afternoon heat left everyone dozing in the shade.",
    wordParts: "Latin 'in-' (not) + 'dolere' (to feel pain) — avoiding exertion." },
  { id: "inept", word: "Inept", difficulty: "Medium",
    definition: "Having no skill; clumsy or incompetent.",
    example: "His inept handling of the crisis only made the panic worse.",
    wordParts: "Latin 'in-' (not) + 'aptus' (suited)." },
  { id: "ingenuous", word: "Ingenuous", difficulty: "Hard",
    definition: "Innocent, sincere, and trusting; free of cunning.",
    example: "Her ingenuous smile made it clear she meant every word.",
    wordParts: "Latin 'ingenuus' (native, freeborn, frank)." },
  { id: "innocuous", word: "Innocuous", difficulty: "Medium",
    definition: "Not harmful or offensive; harmless.",
    example: "What seemed an innocuous comment sparked a week-long argument.",
    wordParts: "Latin 'in-' (not) + 'nocere' (to harm)." },
  { id: "insipid", word: "Insipid", difficulty: "Hard",
    definition: "Lacking flavor or interest; dull and bland.",
    example: "The sequel was insipid, repeating every joke from the first film.",
    wordParts: "Latin 'in-' (not) + 'sapidus' (tasty)." },
  { id: "intrepid", word: "Intrepid", difficulty: "Medium",
    definition: "Fearless and adventurous; showing bold courage.",
    example: "The intrepid explorer crossed the ice field alone in midwinter.",
    wordParts: "Latin 'in-' (not) + 'trepidus' (alarmed)." },
  { id: "inundate", word: "Inundate", difficulty: "Hard",
    definition: "To overwhelm with a great amount; to flood.",
    example: "The office was inundated with applications within an hour of the posting.",
    wordParts: "Latin 'in-' + 'unda' (wave)." },
  { id: "jubilant", word: "Jubilant", difficulty: "Medium",
    definition: "Feeling or expressing great joy; triumphant.",
    example: "The jubilant fans poured onto the field after the final whistle.",
    wordParts: "Latin 'jubilare' (to shout for joy)." },
  { id: "judicious", word: "Judicious", difficulty: "Hard",
    definition: "Showing good judgment; wise and sensible.",
    example: "A judicious use of savings carried the family through a hard year.",
    wordParts: "Latin 'judicium' (judgment)." },
  { id: "juxtapose", word: "Juxtapose", difficulty: "Medium",
    definition: "To place things side by side, especially for contrast.",
    example: "The gallery juxtaposed ancient pottery with modern sculpture.",
    wordParts: "Latin 'juxta' (next to) + 'ponere' (to place)." },
  { id: "laconic", word: "Laconic", difficulty: "Hard",
    definition: "Using very few words; concise to the point of bluntness.",
    example: "His laconic 'We'll see' ended the discussion at once.",
    wordParts: "Greek 'Lakonikos' — after the terse Spartans of Laconia." },
  { id: "lament", word: "Lament", difficulty: "Medium",
    definition: "To express deep grief or regret about something.",
    example: "The village lamented the loss of the old bridge for years.",
    wordParts: "Latin 'lamentum' (a wailing)." },
  { id: "languid", word: "Languid", difficulty: "Hard",
    definition: "Pleasantly slow and relaxed; lacking energy or spirit.",
    example: "They spent languid summer days reading in hammocks by the shore.",
    wordParts: "Latin 'languere' (to be weak, faint)." },
  { id: "lavish", word: "Lavish", difficulty: "Medium",
    definition: "Rich, extravagant, or generous in amount.",
    example: "The host laid out a lavish feast that could have fed the whole street.",
    wordParts: "Old French 'lavasse' (a downpour) — pouring out abundantly." },
  { id: "lethargic", word: "Lethargic", difficulty: "Medium",
    definition: "Sluggish and lacking energy or enthusiasm.",
    example: "The heavy lunch left the whole team lethargic for the rest of the meeting.",
    wordParts: "Greek 'lethargos' (forgetful, drowsy)." },
  { id: "levity", word: "Levity", difficulty: "Hard",
    definition: "Humor or lightness, especially when seriousness is expected.",
    example: "A touch of levity eased the tension in the crowded waiting room.",
    wordParts: "Latin 'levis' (light)." },
  { id: "magnanimous", word: "Magnanimous", difficulty: "Hard",
    definition: "Generous and forgiving, especially toward a rival.",
    example: "In victory she was magnanimous, praising the effort of every opponent.",
    wordParts: "Latin 'magnus' (great) + 'animus' (spirit)." },
  { id: "malleable", word: "Malleable", difficulty: "Medium",
    definition: "Easily shaped or influenced; adaptable.",
    example: "Young minds are malleable, absorbing habits from everyone around them.",
    wordParts: "Latin 'malleus' (hammer) — able to be hammered into shape." },
  { id: "mercurial", word: "Mercurial", difficulty: "Hard",
    definition: "Subject to sudden and unpredictable changes of mood.",
    example: "His mercurial temper made every meeting a gamble.",
    wordParts: "After Mercury, the swift and changeable Roman god." },
  { id: "mundane", word: "Mundane", difficulty: "Medium",
    definition: "Lacking interest or excitement; ordinary and everyday.",
    example: "She escaped the mundane routine of the office through weekend painting.",
    wordParts: "Latin 'mundus' (world) — of the ordinary world." },
  { id: "nefarious", word: "Nefarious", difficulty: "Hard",
    definition: "Wicked or criminal in a way that is deliberate.",
    example: "The detective slowly uncovered the nefarious scheme behind the charity.",
    wordParts: "Latin 'nefas' (wrong, crime)." },
  { id: "negligent", word: "Negligent", difficulty: "Medium",
    definition: "Failing to take proper care in doing something.",
    example: "The company was found negligent for ignoring repeated safety complaints.",
    wordParts: "Latin 'negligere' (to disregard)." },
  { id: "novice", word: "Novice", difficulty: "Easy",
    definition: "A person who is new to and inexperienced in an activity.",
    example: "As a novice climber, she stuck to the gentler trails.",
    wordParts: "Latin 'novicius' (newly arrived), from 'novus' (new)." },
  { id: "nuance", word: "Nuance", difficulty: "Medium",
    definition: "A subtle difference in meaning, expression, or tone.",
    example: "A good translator captures the nuance, not just the literal words.",
    wordParts: "French 'nuance' (shade of color), from Latin 'nubes' (cloud)." },
  { id: "obsolete", word: "Obsolete", difficulty: "Medium",
    definition: "No longer produced or used; out of date.",
    example: "Smartphones made the standalone camera nearly obsolete for casual users.",
    wordParts: "Latin 'obsolescere' (to fall into disuse)." },
  { id: "obstinate", word: "Obstinate", difficulty: "Medium",
    definition: "Stubbornly refusing to change one's opinion or course.",
    example: "Too obstinate to ask directions, he drove in circles for an hour.",
    wordParts: "Latin 'obstinare' (to persist)." },
  { id: "ominous", word: "Ominous", difficulty: "Medium",
    definition: "Suggesting that something bad is about to happen.",
    example: "An ominous silence fell over the stadium before the announcement.",
    wordParts: "Latin 'omen' (a sign, foreboding)." },
  { id: "opulent", word: "Opulent", difficulty: "Medium",
    definition: "Ostentatiously rich and luxurious.",
    example: "The opulent ballroom glittered with chandeliers and gold trim.",
    wordParts: "Latin 'opulentus' (wealthy), from 'ops' (wealth)." },
  { id: "ostracize", word: "Ostracize", difficulty: "Hard",
    definition: "To exclude someone from a group or society.",
    example: "He was ostracized by his teammates after breaking the team's trust.",
    wordParts: "Greek 'ostrakon' (a potsherd used in ancient exile votes)." },

  { id: "malevolent", word: "Malevolent", difficulty: "Hard",
    definition: "Having or showing a wish to do evil to others.",
    example: "A malevolent grin crossed the villain's face as the trap sprang shut.",
    wordParts: "Latin 'male' (badly) + 'velle' (to wish)." },
  { id: "meager", word: "Meager", difficulty: "Medium",
    definition: "Lacking in quantity or quality; scanty.",
    example: "The refugees survived on a meager ration of bread and water.",
    wordParts: "Latin 'macer' (lean, thin)." },
  { id: "munificent", word: "Munificent", difficulty: "Hard",
    definition: "Extremely generous in giving.",
    example: "A munificent donor funded the entire new wing of the hospital.",
    wordParts: "Latin 'munus' (gift) + 'facere' (to make)." },
  { id: "myriad", word: "Myriad", difficulty: "Medium",
    definition: "A countless or extremely large number of things.",
    example: "A myriad of stars appeared once the city lights fell behind them.",
    wordParts: "Greek 'myrias' (ten thousand)." },
  { id: "nostalgia", word: "Nostalgia", difficulty: "Easy",
    definition: "A sentimental longing for the past.",
    example: "The old song filled her with nostalgia for summers long gone.",
    wordParts: "Greek 'nostos' (homecoming) + 'algos' (pain)." },
  { id: "notorious", word: "Notorious", difficulty: "Medium",
    definition: "Famous or well known, typically for something bad.",
    example: "The intersection was notorious for accidents long before the new lights.",
    wordParts: "Latin 'notus' (known)." },
  { id: "obfuscate", word: "Obfuscate", difficulty: "Hard",
    definition: "To make something unclear or difficult to understand.",
    example: "The dense jargon seemed designed to obfuscate rather than explain.",
    wordParts: "Latin 'ob-' + 'fuscare' (to darken), from 'fuscus' (dark)." },
  { id: "oblivious", word: "Oblivious", difficulty: "Medium",
    definition: "Not aware of or not concerned about what is happening around one.",
    example: "Lost in his book, he was oblivious to the crowd forming outside.",
    wordParts: "Latin 'oblivisci' (to forget)." },
  { id: "obsequious", word: "Obsequious", difficulty: "Hard",
    definition: "Obedient or attentive to an excessive, fawning degree.",
    example: "The obsequious waiter agreed with every word the guest said.",
    wordParts: "Latin 'obsequi' (to comply with)." },
  { id: "opaque", word: "Opaque", difficulty: "Medium",
    definition: "Not able to be seen through; also, hard to understand.",
    example: "The rules were so opaque that even the referees disagreed.",
    wordParts: "Latin 'opacus' (shaded, dark)." },
  { id: "paradox", word: "Paradox", difficulty: "Medium",
    definition: "A statement that seems contradictory yet may be true.",
    example: "It is a paradox that the more choices we have, the harder it is to choose.",
    wordParts: "Greek 'para-' (contrary to) + 'doxa' (opinion)." },
  { id: "paramount", word: "Paramount", difficulty: "Medium",
    definition: "More important than anything else; supreme.",
    example: "In surgery, the patient's safety is paramount above all else.",
    wordParts: "Old French 'par' (by) + 'amont' (above)." },
  { id: "partisan", word: "Partisan", difficulty: "Hard",
    definition: "Strongly, often blindly, devoted to a party or cause.",
    example: "The debate turned partisan, with each side cheering only its own.",
    wordParts: "Italian 'partigiano' (a member of a faction)." },
  { id: "paucity", word: "Paucity", difficulty: "Hard",
    definition: "The presence of something in unusually small amounts; scarcity.",
    example: "A paucity of evidence forced the detective to release the suspect.",
    wordParts: "Latin 'paucus' (few)." },
  { id: "penchant", word: "Penchant", difficulty: "Hard",
    definition: "A strong habitual liking for something.",
    example: "She has a penchant for old maps and buys one in every city she visits.",
    wordParts: "French 'pencher' (to incline, lean)." },
  { id: "perfunctory", word: "Perfunctory", difficulty: "Hard",
    definition: "Done as a routine duty, without care or interest.",
    example: "He gave the report a perfunctory nod and moved on to the next item.",
    wordParts: "Latin 'perfungi' (to get through, discharge)." },
  { id: "permeate", word: "Permeate", difficulty: "Medium",
    definition: "To spread throughout; to soak into every part of something.",
    example: "The smell of fresh bread permeated the entire house.",
    wordParts: "Latin 'per-' (through) + 'meare' (to pass)." },
  { id: "pernicious", word: "Pernicious", difficulty: "Hard",
    definition: "Having a harmful effect, especially in a gradual or subtle way.",
    example: "The rumor had a pernicious effect, quietly poisoning years of friendship.",
    wordParts: "Latin 'per-' + 'nex' (death) — deadly." },
  { id: "pertinent", word: "Pertinent", difficulty: "Medium",
    definition: "Relevant or directly related to the matter at hand.",
    example: "She set aside the gossip and asked only pertinent questions.",
    wordParts: "Latin 'pertinere' (to relate to)." },
  { id: "pervasive", word: "Pervasive", difficulty: "Medium",
    definition: "Spreading widely throughout an area or group.",
    example: "A pervasive sense of unease settled over the town after the news.",
    wordParts: "Latin 'per-' (through) + 'vadere' (to go)." },
  { id: "petulant", word: "Petulant", difficulty: "Hard",
    definition: "Childishly sulky or bad-tempered over small things.",
    example: "The petulant toddler flung his spoon when denied a second dessert.",
    wordParts: "Latin 'petulans' (impudent), from 'petere' (to seek)." },
  { id: "philanthropy", word: "Philanthropy", difficulty: "Medium",
    definition: "The desire to help others, expressed through generous giving.",
    example: "Her philanthropy built schools in a dozen villages.",
    wordParts: "Greek 'philos' (loving) + 'anthropos' (human)." },
  { id: "phlegmatic", word: "Phlegmatic", difficulty: "Hard",
    definition: "Calm, unemotional, and hard to excite or disturb.",
    example: "The phlegmatic pilot stayed calm even as the storm shook the plane.",
    wordParts: "Greek 'phlegma', once thought to cause a sluggish temperament." },
  { id: "placid", word: "Placid", difficulty: "Medium",
    definition: "Calm and peaceful, with little movement or disturbance.",
    example: "The placid lake mirrored the mountains without a single ripple.",
    wordParts: "Latin 'placidus' (calm), from 'placere' (to please)." },
  { id: "plausible", word: "Plausible", difficulty: "Medium",
    definition: "Seeming reasonable or probable.",
    example: "His excuse was plausible enough that no one thought to question it.",
    wordParts: "Latin 'plaudere' (to applaud) — worthy of approval." },
  { id: "plethora", word: "Plethora", difficulty: "Medium",
    definition: "An excess or overabundance of something.",
    example: "The menu offered a plethora of choices that overwhelmed first-time guests.",
    wordParts: "Greek 'plethore' (fullness), from 'plethein' (to be full)." },
  { id: "poignant", word: "Poignant", difficulty: "Hard",
    definition: "Evoking a keen sense of sadness or regret; deeply moving.",
    example: "The film's poignant final scene left the whole theater in silence.",
    wordParts: "Latin 'pungere' (to prick, sting)." },
  { id: "ponderous", word: "Ponderous", difficulty: "Hard",
    definition: "Slow and clumsy because of great weight; dull and labored.",
    example: "The ponderous lecture dragged on, heavy with needless detail.",
    wordParts: "Latin 'pondus' (weight)." },
  { id: "precarious", word: "Precarious", difficulty: "Medium",
    definition: "Not securely held or in position; dangerously uncertain.",
    example: "The vase sat in a precarious spot at the very edge of the shelf.",
    wordParts: "Latin 'precarius' (obtained by prayer, uncertain)." },
  { id: "precedent", word: "Precedent", difficulty: "Medium",
    definition: "An earlier event or decision used as a guide for later ones.",
    example: "The ruling set a precedent that courts would follow for decades.",
    wordParts: "Latin 'praecedere' (to go before)." },
  { id: "preclude", word: "Preclude", difficulty: "Hard",
    definition: "To prevent something from happening; to make impossible.",
    example: "A prior commitment precluded her from joining the trip.",
    wordParts: "Latin 'prae-' (before) + 'claudere' (to shut)." },
  { id: "presumptuous", word: "Presumptuous", difficulty: "Hard",
    definition: "Overstepping proper bounds; too bold or forward.",
    example: "It felt presumptuous to rearrange a stranger's furniture uninvited.",
    wordParts: "Latin 'praesumere' (to take beforehand)." },
  { id: "pretentious", word: "Pretentious", difficulty: "Medium",
    definition: "Attempting to impress by affecting greater importance than is real.",
    example: "The pretentious review used ten rare words where one plain word would do.",
    wordParts: "Latin 'praetendere' (to stretch forth, claim)." },
  { id: "prevalent", word: "Prevalent", difficulty: "Medium",
    definition: "Widespread; common in a particular area or time.",
    example: "That superstition was once prevalent across the entire coast.",
    wordParts: "Latin 'praevalere' (to be stronger, prevail)." },
  { id: "proficient", word: "Proficient", difficulty: "Medium",
    definition: "Competent and skilled at doing something.",
    example: "After a year abroad, she was proficient enough to dream in French.",
    wordParts: "Latin 'proficere' (to make progress)." },
  { id: "profound", word: "Profound", difficulty: "Medium",
    definition: "Very great or intense; showing deep insight or knowledge.",
    example: "The loss had a profound effect that changed how he saw the world.",
    wordParts: "Latin 'pro-' (forth) + 'fundus' (bottom) — reaching deep." },
  { id: "proliferate", word: "Proliferate", difficulty: "Hard",
    definition: "To increase rapidly in number; to multiply.",
    example: "Food stalls proliferated along the river as the festival grew.",
    wordParts: "Latin 'proles' (offspring) + 'ferre' (to bear)." },
  { id: "prolific", word: "Prolific", difficulty: "Medium",
    definition: "Producing much fruit, work, or offspring; highly productive.",
    example: "The prolific author published three novels in a single year.",
    wordParts: "Latin 'proles' (offspring) + 'facere' (to make)." },
  { id: "prosaic", word: "Prosaic", difficulty: "Hard",
    definition: "Ordinary and unimaginative; commonplace.",
    example: "Behind the dramatic headline lay a prosaic tale of a lost umbrella.",
    wordParts: "Latin 'prosa' (prose) — plain, like everyday speech." },
  { id: "provocative", word: "Provocative", difficulty: "Medium",
    definition: "Causing a strong reaction, especially deliberate annoyance or thought.",
    example: "The essay's provocative claim set off weeks of heated debate.",
    wordParts: "Latin 'provocare' (to call forth)." },
  { id: "quaint", word: "Quaint", difficulty: "Medium",
    definition: "Attractively old-fashioned or unusual.",
    example: "They stayed in a quaint cottage with a thatched roof and crooked door.",
    wordParts: "Old French 'cointe' (clever, elegant), from Latin 'cognitus'." },
  { id: "quandary", word: "Quandary", difficulty: "Hard",
    definition: "A state of uncertainty over a difficult choice.",
    example: "She was in a quandary over whether to accept the job far from home.",
    wordParts: "Origin uncertain, perhaps mock-Latin from the 1500s." },
  { id: "quell", word: "Quell", difficulty: "Medium",
    definition: "To put an end to, usually by force; to suppress.",
    example: "Officers arrived to quell the disturbance before it spread.",
    wordParts: "Old English 'cwellan' (to kill, suppress)." },
  { id: "querulous", word: "Querulous", difficulty: "Hard",
    definition: "Complaining in a petulant or whining manner.",
    example: "The querulous customer found fault with everything, even the free samples.",
    wordParts: "Latin 'queri' (to complain)." },
  { id: "quixotic", word: "Quixotic", difficulty: "Hard",
    definition: "Extremely idealistic and impractical.",
    example: "His quixotic plan to end all traffic with one app amused the investors.",
    wordParts: "After Don Quixote, the hopelessly idealistic knight." },
  { id: "rancor", word: "Rancor", difficulty: "Hard",
    definition: "Bitter, long-lasting resentment or ill will.",
    example: "Years later, not a trace of rancor remained between the old rivals.",
    wordParts: "Latin 'rancere' (to be rotten, stink)." },
  { id: "rebuke", word: "Rebuke", difficulty: "Medium",
    definition: "To express sharp disapproval or criticism.",
    example: "The referee rebuked both captains for the rough play.",
    wordParts: "Old French 'rebuchier' (to beat back)." },
  { id: "recalcitrant", word: "Recalcitrant", difficulty: "Hard",
    definition: "Stubbornly resistant to authority or control.",
    example: "The recalcitrant mule refused to move no matter how they pulled.",
    wordParts: "Latin 're-' (back) + 'calcitrare' (to kick)." },
  { id: "reconcile", word: "Reconcile", difficulty: "Medium",
    definition: "To restore friendly relations; to make consistent.",
    example: "It took years, but the brothers finally reconciled at their mother's table.",
    wordParts: "Latin 're-' + 'conciliare' (to bring together)." },
  { id: "redundant", word: "Redundant", difficulty: "Medium",
    definition: "No longer needed; repeated unnecessarily.",
    example: "The editor removed the redundant phrase 'each and every.'",
    wordParts: "Latin 'redundare' (to overflow)." },
  { id: "refute", word: "Refute", difficulty: "Medium",
    definition: "To prove a statement or theory to be wrong.",
    example: "A single experiment refuted a claim that had stood for a century.",
    wordParts: "Latin 'refutare' (to drive back, rebut)." },
  { id: "relegate", word: "Relegate", difficulty: "Hard",
    definition: "To assign to a lower or less important position.",
    example: "The old maps were relegated to a dusty box in the basement.",
    wordParts: "Latin 're-' + 'legare' (to send)." },
  { id: "relentless", word: "Relentless", difficulty: "Medium",
    definition: "Unceasingly harsh, strict, or determined.",
    example: "Her relentless practice turned a shaky serve into a weapon.",
    wordParts: "From 'relent' (to soften) + '-less' (without)." },
  { id: "relinquish", word: "Relinquish", difficulty: "Medium",
    definition: "To voluntarily give up or let go of something.",
    example: "He relinquished the title but kept the friendships he'd made along the way.",
    wordParts: "Latin 're-' + 'linquere' (to leave)." },
  { id: "remorse", word: "Remorse", difficulty: "Easy",
    definition: "Deep regret or guilt for a wrong committed.",
    example: "Full of remorse, she wrote a long apology that very night.",
    wordParts: "Latin 're-' + 'mordere' (to bite) — a biting back of conscience." },
  { id: "renounce", word: "Renounce", difficulty: "Medium",
    definition: "To formally give up a claim, belief, or possession.",
    example: "The prince renounced the throne to live quietly by the sea.",
    wordParts: "Latin 're-' + 'nuntiare' (to announce)." },
  { id: "repudiate", word: "Repudiate", difficulty: "Hard",
    definition: "To refuse to accept or be associated with; to reject firmly.",
    example: "The author repudiated the forged letters attributed to her.",
    wordParts: "Latin 'repudium' (a casting off)." },
  { id: "resilient", word: "Resilient", difficulty: "Medium",
    definition: "Able to recover quickly from difficulty or setback.",
    example: "Resilient after every failure, she treated each 'no' as practice.",
    wordParts: "Latin 'resilire' (to leap back)." },
  { id: "resolute", word: "Resolute", difficulty: "Medium",
    definition: "Admirably firm and determined in purpose.",
    example: "Resolute in her goal, she trained through rain, injury, and doubt.",
    wordParts: "Latin 'resolvere' (to loosen, settle)." },
  { id: "reverence", word: "Reverence", difficulty: "Medium",
    definition: "Deep respect mixed with awe.",
    example: "The students spoke of their old teacher with genuine reverence.",
    wordParts: "Latin 'revereri' (to stand in awe of)." },
  { id: "rhetoric", word: "Rhetoric", difficulty: "Medium",
    definition: "The art of persuasive speaking or writing; sometimes, empty language.",
    example: "Beneath the soaring rhetoric, the plan offered no real details.",
    wordParts: "Greek 'rhetorike' (art of the orator)." },
  { id: "robust", word: "Robust", difficulty: "Easy",
    definition: "Strong, healthy, and able to withstand demanding conditions.",
    example: "The bridge was engineered to be robust enough for the worst storms.",
    wordParts: "Latin 'robustus' (strong, oaken), from 'robur' (oak)." },
  { id: "rudimentary", word: "Rudimentary", difficulty: "Medium",
    definition: "Basic or elementary; at an early stage of development.",
    example: "With only a rudimentary grasp of the language, he still made himself understood.",
    wordParts: "Latin 'rudimentum' (first attempt), from 'rudis' (unskilled)." },
  { id: "ruthless", word: "Ruthless", difficulty: "Medium",
    definition: "Having or showing no pity or compassion.",
    example: "Her ruthless focus on results left little room for excuses.",
    wordParts: "From 'ruth' (compassion) + '-less' (without)." },
  { id: "sagacious", word: "Sagacious", difficulty: "Hard",
    definition: "Having keen judgment and deep understanding; wise.",
    example: "The sagacious elder foresaw the drought and stored grain in advance.",
    wordParts: "Latin 'sagax' (keen-scented, perceptive)." },
  { id: "salient", word: "Salient", difficulty: "Hard",
    definition: "Most noticeable or important; standing out.",
    example: "She summarized the salient points in three short bullet lines.",
    wordParts: "Latin 'salire' (to leap) — leaping out at the eye." },
  { id: "sanction", word: "Sanction", difficulty: "Hard",
    definition: "To officially approve; or, a penalty for disobeying a rule.",
    example: "The league sanctioned the new rule, then sanctioned teams that ignored it.",
    wordParts: "Latin 'sancire' (to make sacred, ratify)." },
  { id: "sardonic", word: "Sardonic", difficulty: "Hard",
    definition: "Grimly mocking or cynical.",
    example: "He gave a sardonic smile and said the disaster was 'going great.'",
    wordParts: "Greek 'sardonios' — a bitter, scornful laugh." },
  { id: "scarce", word: "Scarce", difficulty: "Easy",
    definition: "Insufficient for the demand; not plentiful.",
    example: "Clean water grew scarce during the long, rainless summer.",
    wordParts: "Latin 'excerpere' (to pluck out) via Old French." },
  { id: "scrupulous", word: "Scrupulous", difficulty: "Hard",
    definition: "Diligent, thorough, and careful about doing what is right.",
    example: "A scrupulous accountant, he double-checked every figure by hand.",
    wordParts: "Latin 'scrupulus' (a small sharp stone) — a nagging doubt." },
  { id: "serene", word: "Serene", difficulty: "Medium",
    definition: "Calm, peaceful, and untroubled.",
    example: "A serene stillness settled over the garden at dawn.",
    wordParts: "Latin 'serenus' (clear, calm)." },
  { id: "servile", word: "Servile", difficulty: "Hard",
    definition: "Excessively willing to please or obey; submissive.",
    example: "His servile flattery of the boss embarrassed the whole team.",
    wordParts: "Latin 'servus' (slave)." },
  { id: "skeptical", word: "Skeptical", difficulty: "Medium",
    definition: "Not easily convinced; having doubts or reservations.",
    example: "Investors were skeptical of profits that seemed too good to be true.",
    wordParts: "Greek 'skeptikos' (inquiring, thoughtful)." },
  { id: "solace", word: "Solace", difficulty: "Medium",
    definition: "Comfort or consolation in a time of distress.",
    example: "She found solace in long walks after the difficult year.",
    wordParts: "Latin 'solari' (to comfort)." },
  { id: "somber", word: "Somber", difficulty: "Medium",
    definition: "Dark, gloomy, or grave in mood or color.",
    example: "A somber mood filled the hall as the results were read aloud.",
    wordParts: "Latin 'sub-' (under) + 'umbra' (shade)." },
  { id: "sordid", word: "Sordid", difficulty: "Hard",
    definition: "Dirty and squalid; morally distasteful.",
    example: "The article exposed the sordid details behind the company's success.",
    wordParts: "Latin 'sordidus' (dirty), from 'sordes' (filth)." },
  { id: "spontaneous", word: "Spontaneous", difficulty: "Medium",
    definition: "Performed from natural impulse, without planning.",
    example: "A spontaneous cheer erupted the moment the doors opened.",
    wordParts: "Latin 'sponte' (of one's own accord)." },
  { id: "sporadic", word: "Sporadic", difficulty: "Medium",
    definition: "Occurring at irregular intervals; scattered.",
    example: "Sporadic rain interrupted the game throughout the afternoon.",
    wordParts: "Greek 'sporadikos' (scattered), from 'speirein' (to sow)." },
  { id: "squander", word: "Squander", difficulty: "Medium",
    definition: "To waste something valuable in a reckless way.",
    example: "He squandered his savings on schemes that never paid off.",
    wordParts: "Origin uncertain; in use since the 1500s." },
  { id: "stagnant", word: "Stagnant", difficulty: "Medium",
    definition: "Not flowing or moving; showing no growth or activity.",
    example: "Mosquitoes bred in the stagnant water behind the old mill.",
    wordParts: "Latin 'stagnum' (a pool of standing water)." },
  { id: "stoic", word: "Stoic", difficulty: "Medium",
    definition: "Enduring pain or hardship without showing feelings.",
    example: "She remained stoic through the long treatment, never once complaining.",
    wordParts: "Greek 'Stoa' — the porch where Stoic philosophers taught." },
  { id: "strident", word: "Strident", difficulty: "Hard",
    definition: "Loud and harsh; insistently forceful in tone.",
    example: "His strident objections drowned out every quieter voice in the room.",
    wordParts: "Latin 'stridere' (to creak, grate)." },
  { id: "stringent", word: "Stringent", difficulty: "Medium",
    definition: "Strict, precise, and demanding in requirements.",
    example: "Stringent safety checks delayed the launch by two weeks.",
    wordParts: "Latin 'stringere' (to draw tight)." },
  { id: "subtle", word: "Subtle", difficulty: "Medium",
    definition: "So delicate or precise as to be difficult to notice.",
    example: "A subtle change in her tone told him the answer was no.",
    wordParts: "Latin 'subtilis' (fine, delicate)." },
  { id: "succinct", word: "Succinct", difficulty: "Medium",
    definition: "Expressed clearly in few words; brief and to the point.",
    example: "Her succinct reply — 'Not yet' — said everything necessary.",
    wordParts: "Latin 'succingere' (to gird up, tuck in)." },
  { id: "superficial", word: "Superficial", difficulty: "Medium",
    definition: "Concerned only with the surface; lacking depth.",
    example: "A superficial reading missed the argument buried in the footnotes.",
    wordParts: "Latin 'super-' (above) + 'facies' (face)." },
  { id: "superfluous", word: "Superfluous", difficulty: "Hard",
    definition: "Unnecessary, especially through being more than enough.",
    example: "In an emergency, every superfluous word only wastes precious time.",
    wordParts: "Latin 'super-' (over) + 'fluere' (to flow) — overflowing." },
  { id: "surreptitious", word: "Surreptitious", difficulty: "Hard",
    definition: "Done secretly to avoid being noticed.",
    example: "She stole a surreptitious glance at the answer sheet, then looked away.",
    wordParts: "Latin 'surripere' (to snatch secretly)." },
  { id: "sycophant", word: "Sycophant", difficulty: "Hard",
    definition: "A person who flatters powerful people to gain advantage.",
    example: "The king was surrounded by sycophants who never dared to disagree.",
    wordParts: "Greek 'sykophantes' (informer, flatterer)." },
  { id: "tacit", word: "Tacit", difficulty: "Hard",
    definition: "Understood or implied without being stated.",
    example: "Their silence was tacit approval of the plan.",
    wordParts: "Latin 'tacitus' (silent), from 'tacere' (to be silent)." },
  { id: "tangential", word: "Tangential", difficulty: "Hard",
    definition: "Only slightly relevant; diverging from the main point.",
    example: "His answer was tangential, touching everything but the actual question.",
    wordParts: "Latin 'tangere' (to touch) — touching at a single point." },
  { id: "tedious", word: "Tedious", difficulty: "Medium",
    definition: "Too long, slow, or dull; tiresome and monotonous.",
    example: "Copying the figures by hand was tedious but unavoidable work.",
    wordParts: "Latin 'taedium' (weariness)." },
  { id: "temerity", word: "Temerity", difficulty: "Hard",
    definition: "Excessive boldness or nerve; reckless audacity.",
    example: "He had the temerity to correct the professor in front of the class.",
    wordParts: "Latin 'temeritas' (rashness), from 'temere' (rashly)." },
  { id: "tenacious", word: "Tenacious", difficulty: "Medium",
    definition: "Holding firmly to something; persistent and determined.",
    example: "Tenacious to the end, she rewrote the proposal six times.",
    wordParts: "Latin 'tenax' (holding fast), from 'tenere' (to hold)." },
  { id: "terse", word: "Terse", difficulty: "Medium",
    definition: "Brief and to the point, sometimes to the point of rudeness.",
    example: "The terse memo held just four words: 'See me. Bring numbers.'",
    wordParts: "Latin 'tersus' (wiped clean, polished)." },
  { id: "tirade", word: "Tirade", difficulty: "Hard",
    definition: "A long, angry speech of criticism or accusation.",
    example: "A late train set off a tirade about the state of the whole system.",
    wordParts: "Italian 'tirata' (a volley), from 'tirare' (to pull, shoot)." },
  { id: "transient", word: "Transient", difficulty: "Medium",
    definition: "Lasting only a short time; passing quickly.",
    example: "Fame in that industry is transient, forgotten by the next season.",
    wordParts: "Latin 'transire' (to go across, pass)." },
  { id: "trepidation", word: "Trepidation", difficulty: "Hard",
    definition: "A feeling of fear or anxiety about something that may happen.",
    example: "With some trepidation, she opened the letter that would decide her future.",
    wordParts: "Latin 'trepidare' (to tremble)." },
  { id: "trite", word: "Trite", difficulty: "Medium",
    definition: "Overused and lacking freshness or originality.",
    example: "The card's trite verse felt as generic as the flowers that came with it.",
    wordParts: "Latin 'tritus' (worn), from 'terere' (to rub, wear away)." },
  { id: "truncate", word: "Truncate", difficulty: "Medium",
    definition: "To shorten by cutting off the top or end.",
    example: "The system truncated the long file name, hiding its final words.",
    wordParts: "Latin 'truncare' (to lop off), from 'truncus' (trunk)." },
];

export const VOCAB_BY_ID: Record<string, VocabWord> = Object.fromEntries(
  VOCAB.map((w) => [w.id, w])
);
